# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12bf49bcbf43868a257ab487f6e98b3efc84a209383aff6bb5dc770f5277814c58522ca53db202cb67f76968b57c0d91722aefb9e13aea61f1ff9d3a546a4aac

test:
  secret_key_base: 12f935fb844611fc96d74084bff30e47819211a1f07c609d5c63c365efa086ab1ca9beb14157cf1546613a8e833bda85f91937b8f999527531a2fc1829a610a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
